-- Kaki Finder: run this entire file in your Supabase project SQL Editor.
-- Repeatable setup; preserves records and adds account ownership policies.

begin;

-- These profiles are a fictional demo directory. Accounts will get a separate
-- auth-linked profiles table so a seed never overwrites a real person's account.
create table if not exists public.residents (
  id uuid primary key,
  name text not null check (char_length(name) between 1 and 80),
  age_range text not null,
  participant_group text not null check (participant_group in ('young-adult', 'adult', 'senior', 'family')),
  block text not null,
  languages text[] not null check (cardinality(languages) > 0 and languages <@ array['english', 'mandarin', 'tamil', 'malay', 'hokkien']::text[]),
  bio text not null,
  -- Roles are attached to activities, not age groups. JSON keeps this two-day
  -- prototype small while the application validates every nested record.
  intents jsonb not null check (jsonb_typeof(intents) = 'array' and jsonb_array_length(intents) > 0),
  availability jsonb not null check (jsonb_typeof(availability) = 'array'),
  is_demo boolean not null default true check (is_demo = true)
);

create table if not exists public.facilities (
  id uuid primary key,
  name text not null,
  activities text[] not null check (cardinality(activities) > 0),
  openings jsonb not null check (jsonb_typeof(openings) = 'array'),
  is_demo boolean not null default true check (is_demo = true)
);

create table if not exists public.interests (
  id uuid primary key default gen_random_uuid(),
  client_request_id uuid not null unique,
  resident_id uuid not null references public.residents(id),
  request jsonb not null check (jsonb_typeof(request) = 'object'),
  suggested_slot jsonb check (suggested_slot is null or jsonb_typeof(suggested_slot) = 'object'),
  created_at timestamptz not null default now()
);
create index if not exists interests_resident_id_idx on public.interests(resident_id);

-- Only server routes may access these tables. No user-facing interest list is
-- exposed until accounts and ownership policies are implemented.
alter table public.residents enable row level security;
alter table public.facilities enable row level security;
alter table public.interests enable row level security;
revoke all on table public.residents, public.facilities, public.interests from public, anon, authenticated;
grant select, insert, update, delete on table public.residents, public.facilities, public.interests to service_role;

commit;

-- Generated by npm run db:prepare from src/data/*.json. Do not edit by hand.
-- Profiles, facilities, and all times are fictional demo data.
begin;
insert into public.residents (id, name, age_range, participant_group, block, languages, bio, intents, availability, is_demo)
select id, name, age_range, participant_group, block, languages, bio, intents, availability, is_demo
from jsonb_to_recordset('[{"id":"11111111-1111-4111-8111-000000000001","name":"Tan Ah Seng","age_range":"70s","participant_group":"senior","block":"41","languages":["english","mandarin","hokkien"],"bio":"I have played chess at the void deck for years. Come learn a few opening moves, and perhaps you can teach me a guitar chord or two.","intents":[{"activity":"chess","role":"teacher","skill":"beginner chess"},{"activity":"guitar","role":"learner","skill":null},{"activity":"badminton","role":"partner","skill":null}],"availability":[{"day":2,"start":"18:00","end":"21:00"},{"day":4,"start":"18:00","end":"21:00"},{"day":6,"start":"09:00","end":"12:00"},{"day":7,"start":"09:00","end":"12:00"}],"is_demo":true},{"id":"11111111-1111-4111-8111-000000000002","name":"Lim Mei Hwa","age_range":"60s (65–69)","participant_group":"senior","block":"43","languages":["english","mandarin","hokkien"],"bio":"My Hokkien recipes are measured in pinches and happy memories. I would love to pass them on, and learn how to photograph our dishes.","intents":[{"activity":"cooking","role":"teacher","skill":"Hokkien cooking"},{"activity":"photography","role":"learner","skill":null},{"activity":"chess","role":"learner","skill":null}],"availability":[{"day":2,"start":"18:00","end":"21:00"},{"day":4,"start":"18:00","end":"21:00"},{"day":6,"start":"09:00","end":"12:00"},{"day":7,"start":"09:00","end":"12:00"}],"is_demo":true},{"id":"11111111-1111-4111-8111-000000000003","name":"Abdul Rahman","age_range":"70s","participant_group":"senior","block":"45","languages":["english","malay"],"bio":"My corridor is full of herbs and little experiments. Children are welcome to get their hands muddy. I also enjoy a gentle game of badminton.","intents":[{"activity":"gardening","role":"teacher","skill":"herbs and container gardening"},{"activity":"badminton","role":"partner","skill":null},{"activity":"coding","role":"learner","skill":"beginner coding"}],"availability":[{"day":2,"start":"18:00","end":"21:00"},{"day":4,"start":"18:00","end":"21:00"},{"day":6,"start":"09:00","end":"12:00"},{"day":7,"start":"09:00","end":"12:00"}],"is_demo":true},{"id":"11111111-1111-4111-8111-000000000004","name":"Mary D''Souza","age_range":"70s","participant_group":"senior","block":"47","languages":["english","tamil"],"bio":"After years of teaching English, I still love a good story. Bring a book or practise a conversation with me; I am learning chess myself.","intents":[{"activity":"language","role":"teacher","skill":"English tutoring"},{"activity":"chess","role":"learner","skill":null},{"activity":"gardening","role":"learner","skill":null}],"availability":[{"day":2,"start":"18:00","end":"21:00"},{"day":4,"start":"18:00","end":"21:00"},{"day":6,"start":"09:00","end":"12:00"},{"day":7,"start":"09:00","end":"12:00"}],"is_demo":true},{"id":"11111111-1111-4111-8111-000000000005","name":"Lakshmi Subramaniam","age_range":"60s (65–69)","participant_group":"senior","block":"49","languages":["english","tamil"],"bio":"Traditional dance has kept me smiling for decades. I can share gentle beginner steps, and would love some help getting started with a fitness routine.","intents":[{"activity":"dance","role":"teacher","skill":"traditional Indian dance"},{"activity":"fitness","role":"learner","skill":null},{"activity":"cooking","role":"learner","skill":"Hokkien cooking"}],"availability":[{"day":2,"start":"18:00","end":"21:00"},{"day":4,"start":"18:00","end":"21:00"},{"day":6,"start":"09:00","end":"12:00"},{"day":7,"start":"09:00","end":"12:00"}],"is_demo":true},{"id":"11111111-1111-4111-8111-000000000006","name":"Cheryl Tan","age_range":"20s","participant_group":"young-adult","block":"41","languages":["english","mandarin"],"bio":"I work near Novena and would love to know the neighbours I wave to. Happy to organise a friendly badminton game, or learn chess over a kopi.","intents":[{"activity":"badminton","role":"partner","skill":null},{"activity":"chess","role":"learner","skill":"beginner chess"},{"activity":"cooking","role":"learner","skill":"Hokkien cooking"}],"availability":[{"day":2,"start":"18:00","end":"21:00"},{"day":4,"start":"18:00","end":"21:00"},{"day":6,"start":"09:00","end":"12:00"},{"day":7,"start":"09:00","end":"12:00"}],"is_demo":true},{"id":"11111111-1111-4111-8111-000000000007","name":"Muhammad Irfan","age_range":"30s","participant_group":"young-adult","block":"43","languages":["english","malay"],"bio":"I build software by day and am happy to explain coding slowly, one step at a time. My balcony plants could use an experienced neighbour''s advice.","intents":[{"activity":"coding","role":"teacher","skill":"beginner coding"},{"activity":"gardening","role":"learner","skill":null},{"activity":"chess","role":"learner","skill":null}],"availability":[{"day":2,"start":"18:00","end":"21:00"},{"day":4,"start":"18:00","end":"21:00"},{"day":6,"start":"09:00","end":"12:00"},{"day":7,"start":"09:00","end":"12:00"}],"is_demo":true},{"id":"11111111-1111-4111-8111-000000000008","name":"Priya Nair","age_range":"20s","participant_group":"young-adult","block":"45","languages":["english","tamil"],"bio":"I have a spare guitar and plenty of patience. I would love to trade a few beginner chords for a cooking lesson or a new friendship.","intents":[{"activity":"guitar","role":"teacher","skill":"beginner guitar"},{"activity":"cooking","role":"learner","skill":"Hokkien cooking"},{"activity":"dance","role":"learner","skill":"traditional Indian dance"}],"availability":[{"day":2,"start":"18:00","end":"21:00"},{"day":4,"start":"18:00","end":"21:00"},{"day":6,"start":"09:00","end":"12:00"},{"day":7,"start":"09:00","end":"12:00"}],"is_demo":true},{"id":"11111111-1111-4111-8111-000000000009","name":"Daniel Wong","age_range":"30s","participant_group":"young-adult","block":"47","languages":["english","mandarin"],"bio":"An evening walk helps me unwind after work. I can share gentle exercise ideas, and I am always keen for badminton or a gardening lesson.","intents":[{"activity":"fitness","role":"teacher","skill":"gentle fitness"},{"activity":"badminton","role":"partner","skill":null},{"activity":"jogging","role":"partner","skill":null},{"activity":"gardening","role":"learner","skill":null}],"availability":[{"day":2,"start":"18:00","end":"21:00"},{"day":4,"start":"18:00","end":"21:00"},{"day":6,"start":"09:00","end":"12:00"},{"day":7,"start":"09:00","end":"12:00"}],"is_demo":true},{"id":"11111111-1111-4111-8111-000000000010","name":"Nur Aisyah","age_range":"30s","participant_group":"young-adult","block":"49","languages":["english","malay"],"bio":"I enjoy photographing everyday moments around Pek Kio. I can show you how to take a lovely phone photo, and would be delighted to learn a family recipe.","intents":[{"activity":"photography","role":"teacher","skill":"phone photography"},{"activity":"cooking","role":"learner","skill":"Hokkien cooking"},{"activity":"language","role":"learner","skill":"Mandarin conversation"},{"activity":"chess","role":"teacher","skill":"beginner chess"}],"availability":[{"day":2,"start":"18:00","end":"21:00"},{"day":4,"start":"18:00","end":"21:00"},{"day":6,"start":"09:00","end":"12:00"},{"day":7,"start":"09:00","end":"12:00"}],"is_demo":true},{"id":"11111111-1111-4111-8111-000000000011","name":"Jason & Wei Ling","age_range":"Parents in their 40s","participant_group":"family","block":"41","languages":["english","mandarin"],"bio":"Our eight-year-old asks how every leaf grows. We would love to garden with an experienced neighbour and learn chess together as a family.","intents":[{"activity":"gardening","role":"learner","skill":"herbs and container gardening"},{"activity":"chess","role":"learner","skill":"beginner chess"},{"activity":"cooking","role":"learner","skill":"Hokkien cooking"}],"availability":[{"day":6,"start":"09:00","end":"12:00"},{"day":7,"start":"09:00","end":"12:00"}],"is_demo":true},{"id":"11111111-1111-4111-8111-000000000012","name":"Siti & Farid","age_range":"Parents in their 30s","participant_group":"family","block":"43","languages":["english","malay"],"bio":"Our children love helping in the kitchen and meeting the aunties and uncles nearby. We can share Malay conversation and would enjoy learning to grow herbs.","intents":[{"activity":"gardening","role":"learner","skill":null},{"activity":"cooking","role":"learner","skill":null},{"activity":"language","role":"teacher","skill":"Malay conversation"},{"activity":"language","role":"learner","skill":"English tutoring"}],"availability":[{"day":6,"start":"09:00","end":"12:00"},{"day":7,"start":"09:00","end":"12:00"}],"is_demo":true},{"id":"11111111-1111-4111-8111-000000000013","name":"Arun & Kavitha","age_range":"Parents in their 40s","participant_group":"family","block":"45","languages":["english","tamil"],"bio":"We would like our children to know the people behind the friendly waves in our block. Gardening, traditional dance, and stories in another language sound lovely.","intents":[{"activity":"gardening","role":"learner","skill":null},{"activity":"dance","role":"learner","skill":"traditional Indian dance"},{"activity":"language","role":"learner","skill":"Mandarin conversation"},{"activity":"language","role":"teacher","skill":"Tamil conversation"}],"availability":[{"day":6,"start":"09:00","end":"12:00"},{"day":7,"start":"09:00","end":"12:00"}],"is_demo":true},{"id":"11111111-1111-4111-8111-000000000014","name":"Grace & Samuel","age_range":"Parents in their 30s","participant_group":"family","block":"47","languages":["english","mandarin"],"bio":"We are raising two curious little cooks. We would love to learn Hokkien dishes and enjoy conversation with neighbours from another generation.","intents":[{"activity":"cooking","role":"learner","skill":"Hokkien cooking"},{"activity":"language","role":"teacher","skill":"Mandarin conversation"},{"activity":"language","role":"learner","skill":"Malay conversation"},{"activity":"gardening","role":"teacher","skill":"herbs and container gardening"}],"availability":[{"day":6,"start":"09:00","end":"12:00"},{"day":7,"start":"09:00","end":"12:00"}],"is_demo":true},{"id":"11111111-1111-4111-8111-000000000015","name":"Goh Kok Leong","age_range":"40s","participant_group":"adult","block":"49","languages":["english","mandarin","hokkien"],"bio":"I am usually up for an easy jog or a relaxed badminton game. Beginners are welcome; good company matters more than keeping score.","intents":[{"activity":"badminton","role":"partner","skill":null},{"activity":"jogging","role":"partner","skill":null},{"activity":"cooking","role":"teacher","skill":"Hokkien cooking"},{"activity":"chess","role":"learner","skill":null}],"availability":[{"day":2,"start":"18:00","end":"21:00"},{"day":4,"start":"18:00","end":"21:00"},{"day":6,"start":"09:00","end":"12:00"},{"day":7,"start":"09:00","end":"12:00"}],"is_demo":true}]'::jsonb) as r(
  id uuid, name text, age_range text, participant_group text, block text,
  languages text[], bio text, intents jsonb, availability jsonb, is_demo boolean
)
on conflict (id) do update set
  name = excluded.name, age_range = excluded.age_range, participant_group = excluded.participant_group,
  block = excluded.block, languages = excluded.languages, bio = excluded.bio,
  intents = excluded.intents, availability = excluded.availability;

insert into public.facilities (id, name, activities, openings, is_demo)
select id, name, activities, openings, is_demo
from jsonb_to_recordset('[{"id":"22222222-2222-4222-8222-000000000001","name":"Badminton court (demo)","activities":["badminton"],"openings":[{"day":2,"start":"18:00","end":"21:00"},{"day":4,"start":"18:00","end":"21:00"},{"day":6,"start":"09:00","end":"12:00"},{"day":7,"start":"09:00","end":"12:00"}],"is_demo":true},{"id":"22222222-2222-4222-8222-000000000002","name":"Cooking classroom (demo)","activities":["cooking"],"openings":[{"day":2,"start":"18:00","end":"21:00"},{"day":4,"start":"18:00","end":"21:00"},{"day":6,"start":"09:00","end":"12:00"},{"day":7,"start":"09:00","end":"12:00"}],"is_demo":true},{"id":"22222222-2222-4222-8222-000000000003","name":"Dance studio (demo)","activities":["dance","fitness"],"openings":[{"day":2,"start":"18:00","end":"21:00"},{"day":4,"start":"18:00","end":"21:00"},{"day":6,"start":"09:00","end":"12:00"},{"day":7,"start":"09:00","end":"12:00"}],"is_demo":true},{"id":"22222222-2222-4222-8222-000000000004","name":"Community activity room (demo)","activities":["chess","language","coding","guitar","photography"],"openings":[{"day":2,"start":"18:00","end":"21:00"},{"day":4,"start":"18:00","end":"21:00"},{"day":6,"start":"09:00","end":"12:00"},{"day":7,"start":"09:00","end":"12:00"}],"is_demo":true},{"id":"22222222-2222-4222-8222-000000000005","name":"Gardening and outdoor meeting area (demo)","activities":["gardening","jogging"],"openings":[{"day":2,"start":"18:00","end":"21:00"},{"day":4,"start":"18:00","end":"21:00"},{"day":6,"start":"09:00","end":"12:00"},{"day":7,"start":"09:00","end":"12:00"}],"is_demo":true}]'::jsonb) as f(
  id uuid, name text, activities text[], openings jsonb, is_demo boolean
)
on conflict (id) do update set
  name = excluded.name, activities = excluded.activities, openings = excluded.openings;
commit;
notify pgrst, 'reload schema';

begin;
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 80),
  block text not null check (char_length(block) between 1 and 20),
  participant_group text not null check (participant_group in ('young-adult', 'adult', 'senior', 'family')),
  languages text[] not null check (cardinality(languages) between 1 and 5 and languages <@ array['english','mandarin','tamil','malay','hokkien']::text[]),
  bio text not null default '' check (char_length(bio) <= 600)
);
-- Existing guest interests remain unowned. Names and blocks are not proof of identity.
alter table public.interests add column if not exists user_id uuid references auth.users(id) on delete cascade;
create index if not exists interests_user_created_idx on public.interests(user_id, created_at desc);
alter table public.profiles enable row level security;
revoke all on public.profiles from public, anon, authenticated;
grant select, insert, update on public.profiles to authenticated;
grant all on public.profiles to service_role;
grant select, insert, delete on public.interests to authenticated;

drop policy if exists profiles_read_own on public.profiles;
create policy profiles_read_own on public.profiles for select to authenticated using ((select auth.uid()) = id);
drop policy if exists profiles_insert_own on public.profiles;
create policy profiles_insert_own on public.profiles for insert to authenticated with check ((select auth.uid()) = id);
drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
drop policy if exists interests_read_own on public.interests;
create policy interests_read_own on public.interests for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists interests_insert_own on public.interests;
create policy interests_insert_own on public.interests for insert to authenticated with check ((select auth.uid()) = user_id);
drop policy if exists interests_delete_own on public.interests;
create policy interests_delete_own on public.interests for delete to authenticated using ((select auth.uid()) = user_id);
commit;
notify pgrst, 'reload schema';

begin;

-- Publication is an explicit choice. Existing accounts start private.
alter table public.profiles add column if not exists discoverable boolean not null default false;
alter table public.profiles add column if not exists intents jsonb not null default '[]'::jsonb;
alter table public.profiles add column if not exists availability jsonb not null default '[]'::jsonb;
alter table public.profiles add column if not exists directory_id uuid not null default gen_random_uuid();
create unique index if not exists profiles_directory_id_idx on public.profiles(directory_id);

create or replace function public.valid_discovery_details(intents jsonb, availability jsonb)
returns boolean language plpgsql immutable set search_path = '' as $$
declare item jsonb;
begin
  if jsonb_typeof(intents) <> 'array' or jsonb_typeof(availability) <> 'array' then return false; end if;
  if jsonb_array_length(intents) > 20 or jsonb_array_length(availability) > 21 then return false; end if;
  for item in select value from jsonb_array_elements(intents) loop
    if jsonb_typeof(item) <> 'object' or not (item ?& array['activity','role','skill']) then return false; end if;
    if (item - array['activity','role','skill']) <> '{}'::jsonb then return false; end if;
    if (item->>'activity') is null or (item->>'activity') not in ('chess','cooking','gardening','language','dance','badminton','coding','guitar','fitness','photography','jogging') then return false; end if;
    if (item->>'role') is null or (item->>'role') not in ('teacher','learner','partner') then return false; end if;
    if item->'skill' <> 'null'::jsonb and (jsonb_typeof(item->'skill') <> 'string' or char_length(btrim(item->>'skill')) not between 1 and 120) then return false; end if;
  end loop;
  for item in select value from jsonb_array_elements(availability) loop
    if jsonb_typeof(item) <> 'object' or not (item ?& array['day','start','end']) then return false; end if;
    if (item - array['day','start','end']) <> '{}'::jsonb then return false; end if;
    if jsonb_typeof(item->'day') <> 'number' or (item->>'day') !~ '^[1-7]$' then return false; end if;
    if jsonb_typeof(item->'start') <> 'string' or jsonb_typeof(item->'end') <> 'string' then return false; end if;
    if (item->>'start') !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' or (item->>'end') !~ '^([01][0-9]|2[0-3]):[0-5][0-9]$' or (item->>'start') >= (item->>'end') then return false; end if;
  end loop;
  return true;
end;
$$;
revoke all on function public.valid_discovery_details(jsonb,jsonb) from public;
grant execute on function public.valid_discovery_details(jsonb,jsonb) to authenticated, service_role;
alter table public.profiles drop constraint if exists profiles_discovery_details_check;
alter table public.profiles add constraint profiles_discovery_details_check check (public.valid_discovery_details(intents, availability));
alter table public.profiles drop constraint if exists profiles_publication_check;
alter table public.profiles add constraint profiles_publication_check check (not discoverable or (jsonb_array_length(intents) > 0 and jsonb_array_length(availability) > 0 and char_length(btrim(bio)) > 0));

alter table public.residents drop constraint if exists residents_is_demo_check;
alter table public.residents add column if not exists owner_id uuid unique references auth.users(id) on delete set null;
alter table public.residents add column if not exists is_active boolean not null default true;

-- A separate public ID avoids exposing auth IDs. Clients cannot choose or change it.
revoke insert, update on public.profiles from authenticated;
grant insert(id,name,block,participant_group,languages,bio,discoverable,intents,availability) on public.profiles to authenticated;
grant update(id,name,block,participant_group,languages,bio,discoverable,intents,availability) on public.profiles to authenticated;

-- Only this trigger can project private profile fields into the server-only directory.
-- The fixed search path prevents caller-created objects from changing its behaviour.
create or replace function public.sync_discoverable_profile()
returns trigger language plpgsql security definer set search_path = '' as $$
begin
  if tg_op = 'DELETE' then
    update public.residents set is_active = false where id = old.directory_id;
    return old;
  end if;
  if not new.discoverable then
    update public.residents set is_active = false where id = new.directory_id;
    return new;
  end if;
  insert into public.residents(id,owner_id,name,age_range,participant_group,block,languages,bio,intents,availability,is_demo,is_active)
  values(new.directory_id,new.id,new.name,
    case new.participant_group when 'young-adult' then '20–40' when 'adult' then '41–64' when 'senior' then '65+' else 'Family (adult-managed)' end,
    new.participant_group,new.block,new.languages,new.bio,new.intents,new.availability,false,true)
  on conflict(id) do update set name=excluded.name, age_range=excluded.age_range,
    participant_group=excluded.participant_group, block=excluded.block, languages=excluded.languages,
    bio=excluded.bio, intents=excluded.intents, availability=excluded.availability, is_active=true
  where public.residents.owner_id = new.id;
  return new;
end;
$$;
revoke all on function public.sync_discoverable_profile() from public, anon, authenticated;
drop trigger if exists sync_discoverable_profile on public.profiles;
create trigger sync_discoverable_profile after insert or update or delete on public.profiles for each row execute function public.sync_discoverable_profile();

-- Lock the target during insertion so hiding and expressing interest cannot race.
create or replace function public.check_interest_target()
returns trigger language plpgsql security definer set search_path = '' as $$
declare target public.residents%rowtype;
begin
  select * into target from public.residents where id = new.resident_id for share;
  if not found or not target.is_active or (new.user_id is not null and target.owner_id = new.user_id) then
    raise exception 'This neighbour is no longer available' using errcode = '23514';
  end if;
  return new;
end;
$$;
revoke all on function public.check_interest_target() from public, anon, authenticated;
drop trigger if exists check_interest_target on public.interests;
create trigger check_interest_target before insert on public.interests for each row execute function public.check_interest_target();
commit;
notify pgrst, 'reload schema';
