import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = relative => readFileSync(path.join(root, relative), 'utf8');
const residents = JSON.parse(read('src/data/residents.json')).map(r => ({
  id: r.id, name: r.name, age_range: r.ageRange, participant_group: r.participantGroup,
  block: r.block, languages: r.languages, bio: r.bio, intents: r.intents,
  availability: r.availability, is_demo: true,
}));
const facilities = JSON.parse(read('src/data/facilities.json')).map(f => ({
  id: f.id, name: f.name, activities: f.activities, openings: f.openings, is_demo: f.isDemo,
}));
// Escape SQL literals rather than interpolating unescaped profile prose.
const jsonLiteral = value => "'" + JSON.stringify(value).replaceAll("'", "''") + "'::jsonb";
const seed = `-- Generated by npm run db:prepare from src/data/*.json. Do not edit by hand.
-- Profiles, facilities, and all times are fictional demo data.
begin;
insert into public.residents (id, name, age_range, participant_group, block, languages, bio, intents, availability, is_demo)
select id, name, age_range, participant_group, block, languages, bio, intents, availability, is_demo
from jsonb_to_recordset(${jsonLiteral(residents)}) as r(
  id uuid, name text, age_range text, participant_group text, block text,
  languages text[], bio text, intents jsonb, availability jsonb, is_demo boolean
)
on conflict (id) do update set
  name = excluded.name, age_range = excluded.age_range, participant_group = excluded.participant_group,
  block = excluded.block, languages = excluded.languages, bio = excluded.bio,
  intents = excluded.intents, availability = excluded.availability;

insert into public.facilities (id, name, activities, openings, is_demo)
select id, name, activities, openings, is_demo
from jsonb_to_recordset(${jsonLiteral(facilities)}) as f(
  id uuid, name text, activities text[], openings jsonb, is_demo boolean
)
on conflict (id) do update set
  name = excluded.name, activities = excluded.activities, openings = excluded.openings;
commit;
notify pgrst, 'reload schema';
`;
writeFileSync(path.join(root, 'supabase/seeds/demo.sql'), seed);
const migration = read('supabase/migrations/202609050001_community_data.sql');
writeFileSync(path.join(root, 'supabase/setup.sql'), '-- Kaki Finder: run this entire file in your Supabase project SQL Editor.\n-- Repeatable setup; does not delete interest records or create accounts.\n\n' + migration + '\n' + seed);
console.log('Prepared supabase/setup.sql: 15 residents, 5 demo facilities, private interest storage.');
